### ISSUE TITLE
DSL ERROR

### ISSUE THREAD

**Issue by liaction** [JetBrains/anko#105]
class MainActivity: Activity() {
	    override fun onCreate(savedInstanceState: Bundle?) {
	        super.onCreate(savedInstanceState)
	        verticalLayout {
	            textView {
	                text = "Hello Kotlin !"
	            }
	        }
	    }
	}

open the DSL Preview  and press Refresh 

org.jetbrains.android.facet.AndroidFacet.isGradleProject()Z
java.lang.NoSuchMethodError: org.jetbrains.android.facet.AndroidFacet.isGradleProject()Z
	at org.jetbrains.kotlin.android.dslpreview.DslPreviewToolWindowManager.render(DslPreviewToolWindowManager.kt:265)
	at org.jetbrains.kotlin.android.dslpreview.DslPreviewToolWindowManager$RefreshDslAction.actionPerformed(DslPreviewToolWindowManager.kt:365)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:163)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:127)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:304)
	at java.awt.Component.processEvent(Component.java:6270)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4861)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:723)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:682)
	at java.awt.EventQueue$3.run(EventQueue.java:680)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:696)
	at java.awt.EventQueue$4.run(EventQueue.java:694)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:693)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:244)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:163)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:151)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:147)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:139)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:97)

(kotlin 1.0.0-beta-1103 and anko 0.7.2)

**Comment by NataliaUkhorskaya** [comment]
Which version of Android Studio or IDEA do you use?

**Comment by liaction** [comment]
Android Studio 1.4   AI-141.2343393

Android Studio 1.5 Preview    AI-141.2343905

 They have the same error .

 Thank you ！！！

**Comment by 8enet** [comment]
yes, it's all the same to me!
Android Studio 1.5 Beta AI-141.2384911
Anko DSL Preview version 0.7.3
Kotlin plugin version 1.0.0-beta-1103-IJ141-23

**Comment by yanex** [comment]
Duplicated by #72.
