### ISSUE TITLE
_ScrollView does not implement MarginLayoutParams receiver

### ISSUE THREAD

**Issue by brennantaylor** [JetBrains/anko#54]
The example will repro the stacktrace at the bottom on Android 5.0.0

You may need a theme with the actionbar enabled. I am using `android:Theme.Material.Light.DarkActionBar`

````kotlin
class MainActivity() : Activity() {
    override fun onCreate(state: Bundle?) {
        super.onCreate(state)

        scrollView {
            verticalLayout {
                editText()
            }.layoutParams() {}
        }
    }
}
````

````text
  java.lang.ClassCastException: android.view.ViewGroup$LayoutParams cannot be cast to android.view.ViewGroup$MarginLayoutParams
      at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1252)
      at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
      at android.widget.ScrollView.onMeasure(ScrollView.java:337)
      at android.view.View.measure(View.java:17430)
      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
      at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
````

**Comment by yanex** [comment]
Fixed.
