### ISSUE TITLE
org.jetbrains.anko.AnkoException: Can't initialize object parser for ... , no acceptable constructors found

### ISSUE THREAD

**Issue by SeppPenner** [JetBrains/anko#609]
Hi,

I'm getting the following error message when using Anko SQLite:

> E/AndroidRuntime: FATAL EXCEPTION: main
>                   Process: example.exampleproject, PID: 5636
>                   java.lang.RuntimeException: Unable to start activity ComponentInfo{example.exampleproject/example.exampleproject.activities.FlowActivity}: org.jetbrains.anko.AnkoException: Can't initialize object parser for example.exampleproject.data.FuelData, no acceptable constructors found
>                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3253)
>                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
>                       at android.app.ActivityThread.access$1100(ActivityThread.java:221)
>                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
>                       at android.os.Handler.dispatchMessage(Handler.java:102)
>                       at android.os.Looper.loop(Looper.java:158)
>                       at android.app.ActivityThread.main(ActivityThread.java:7224)
>                       at java.lang.reflect.Method.invoke(Native Method)
>                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
>                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
>                    Caused by: org.jetbrains.anko.AnkoException: Can't initialize object parser for example.exampleproject.data.FuelData, no acceptable constructors found
>                       at org.jetbrains.anko.db.ClassParserKt.classParser(ClassParser.kt:39)
>                       at example.exampleproject.activities.FlowActivity$readFuelData$1.invoke(FlowActivity.kt:61)
>                       at example.exampleproject.activities.FlowActivity$readFuelData$1.invoke(FlowActivity.kt:18)
>                       at org.jetbrains.anko.db.ManagedSQLiteOpenHelper.use(Database.kt:177)
>                       at example.exampleproject.activities.FlowActivity.readFuelData(FlowActivity.kt:52)
>                       at example.exampleproject.activities.FlowActivity.getFuelDataAsEntries(FlowActivity.kt:41)
>                       at example.exampleproject.activities.FlowActivity.setupLineChart(FlowActivity.kt:31)
>                       at example.exampleproject.activities.FlowActivity.onCreate(FlowActivity.kt:26)
>                       at android.app.Activity.performCreate(Activity.java:6876)
>                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
>                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
>                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
>                       at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
>                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
>                       at android.os.Handler.dispatchMessage(Handler.java:102) 
>                       at android.os.Looper.loop(Looper.java:158) 
>                       at android.app.ActivityThread.main(ActivityThread.java:7224) 
>                       at java.lang.reflect.Method.invoke(Native Method) 
>                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
>                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 

My data class looks like the following:

```kotlin
package example.exampleproject.data

import java.util.*

class FuelData(
        val id : Int,
        val fueled: Double,
        val kilometers: Double,
        val mileage: Double,
        val consumption: Double,
        val currentDate: Date
)
```

The function that fails is the following:

```kotlin
private fun readFuelData():List<FuelData>{
        var resultList = ArrayList<FuelData>()
        database.use {
            select("FuelData", "id", "fueled", "kilometers", "mileage", "consumption", "currentDate")
                    .parseList(classParser<FuelData>()).forEach {
                fuelData -> resultList.add(fuelData)
            }
        }
        return resultList
    }
```

I guess the error has something to do with a wrong constructor and the classParser<FuelData>() call?
Do you have any ideas here?

**Comment by SeppPenner** [comment]
I found the issue: class org.jetbrains.anko.db.ClassParser.kt:

```kotlin
private fun hasApplicableType(type: Class<*>): Boolean {
    if (type.isPrimitive) {
        return true
    }

    return when (type) {
        java.lang.String::class.java, java.lang.CharSequence::class.java,
        java.lang.Long::class.java, java.lang.Integer::class.java,
        java.lang.Byte::class.java, java.lang.Character::class.java,
        java.lang.Boolean::class.java, java.lang.Float::class.java,
        java.lang.Double::class.java, java.lang.Short::class.java -> true
        else -> false
    }
}
```

and I used a Date datatype in the class, SQLite only supports the above datatypes.
