### ISSUE TITLE
Multiple dex files define Lorg/jetbrains/anko/AnkoPackage

### ISSUE THREAD

**Issue by Ribesg** [JetBrains/anko#91]
This error appeared just after upgrading to Anko 0.7.1.

````:XXX:dexDebug
Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexException: Multiple dex files define Lorg/jetbrains/anko/AnkoPackage;
Unknown source file :   at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
Unknown source file :   at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
Unknown source file :   at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
Unknown source file :   at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Unknown source file :   at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
Unknown source file :   at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
Unknown source file :   at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
Unknown source file :   at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file :   at com.android.dx.command.dexer.Main.main(Main.java:245)
Unknown source file :   at com.android.dx.command.Main.main(Main.java:106)

:XXX:dexDebug FAILED
````

````groovy
buildscript {
    ext.kotlin_version = '0.14.449'
    repositories {
        jcenter()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId 'fr.ribesg.android.xxx'
        minSdkVersion 15
        targetSdkVersion 23
        versionName '0.0.1'
        versionCode 1
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])

    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.android.support:design:23.0.1'
    compile 'com.android.support:recyclerview-v7:23.0.1'

    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"

    compile 'org.jetbrains.anko:anko-sdk15:0.7.1'
    compile 'org.jetbrains.anko:anko-appcompat-v7:0.7.1'
    compile 'org.jetbrains.anko:anko-design:0.7.1'
    compile 'org.jetbrains.anko:anko-recyclerview-v7:0.7.1'

    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'fuel:fuel:0.55'
}
````

I have no idea if I did something wrong? This set of libs worked just before upgrading.

**Comment by yanex** [comment]
Could you please try jars from here https://github.com/JetBrains/anko/releases/tag/v0.7.1 ? If all is ok, I will re-upload fixed artefacts to Maven.

**Comment by Ribesg** [comment]
I have no idea how I could "try jars from here" as I'm referencing the repository. Adding the jars in local folder 'libs' doesn't work.

**Comment by yoavst** [comment]
+1

**Comment by rainerborene** [comment]
Same here.

**Comment by Ribesg** [comment]
We really need a fix for this!

**Comment by sidius** [comment]
Jars are working fine. Waiting for fixed maven artifacts.

**Comment by yanex** [comment]
Fixed JARs are available on Gradle.

**Comment by yoavst** [comment]
@yanex So what was the problem on the maven artifacts? for general knowledge.

**Comment by Ribesg** [comment]
As this was a release, Gradle, like Maven, doesn't try and get new release package of the same version. After removing `~/.gradle/caches` (Or `X:\Users\Y\.gradle\caches` on Windows), Gradle successfully downloads the entire internet again and it compiles successfully. Thanks!
